server:
  port: 8080
# DB_URL=localhost:5432/goshield;DB_PASSWORD=goshieldudaipur;DB_USERNAME=goshield
spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/goshield"
    username: goshield
    password: goshieldudaipur
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: vs1328@gmail.com
    password: Ghill/1328
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
